[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mysgen"
version = "0.3.0"
description = "My simple static site generator."
license = { text = "MIT" }
readme = "README.md"
authors = [
    { name = "Mladen Gibanica", email = "11275336+mgcth@users.noreply.github.com" },
]
requires-python = ">=3.9"
dependencies = [
    "Markdown ~= 3.3",
    "Pillow ~= 9.0",
    "jinja2 ~= 2.11",
    "python-markdown-math ~= 0.8",
    "MarkupSafe ~= 2.0",
]

[project.optional-dependencies]
test = ["pytest ~= 7.1"]
dev = ["pytest ~= 7.1", "black ~= 22.8", "flake8 ~= 5.0", "pre-commit ~= 2.20"]
